#import "../LinkListWithCountFragment.gql"

query LinkLists(
    $spaceIds: [ID!],
    $forMapping: ID,
    $forNode: ID,
    $forLists: [ID!],
) {
    linkLists(
        spaceIds: $spaceIds,
        forLists: $forLists,
        first: 100,
    ) {
        edges {
            node {
                ...LinkListWithCount
            }
        }
        pageInfo {
            endCursor
            hasNextPage
        }
    }
}
