query LinkStats(
    $forMapping: ID,
    $forLists: [ID!],
    $forNode: ID,
) {
    linkStats(
        forMapping: $forMapping,
        forLists: $forLists,
        forNode: $forNode,
    ) {
        favoritesCount
        totalCount
    }
}
