#import "../DocumentFragment.gql"
#import "../../FetchesActionsFragment.gql"

query Document(
    $id: ID!
) {
    document(
        id: $id
    ) {
        ...Document
        ...FetchesActionsFragment
    }
}
