fragment AssociationCollection on Associatable {
    associations {
        id
        spaceId
        name
        image { url }
        mapping {
            id
            name
        }
        pages {
            id
            name
            symbol
        }
    }
}
