#import "../../spaces/SpaceFragment.gql"
#import "../FullPageFragment.gql"
#import "../../savedFilters/SavedFilterFragment.gql"

query Page($id: ID!) {
    page(id: $id) {
        ...FullPage
    }
}
