#import './ImportFragment.gql'

mutation ImportFile($input: ImportSpreadsheetInput!) {
    importSpreadsheet(input: $input) {
        code
        success
        message
        import {
            ...Import
        }
    }
}
