#import '../MemberFragment.gql'
#import '../progress-tracker/ProgressTrackerFragment.gql'

fragment Import on Import {
    id
    name
    filename
    createdAt
    updatedAt
    member {
        ...MemberFragment
    }
    progress {
        ...ProgressTracker
    }
}
