#import "./ImportFragment.gql"

mutation RevertImport($input: RevertImportInput!) {
    revertImport(input: $input) {
        code
        success
        message
        import {
            ...Import
        }
    }
}
