#import "../MemberFragment.gql"

fragment AssigneeCollection on Assignable {
    assigneeGroups {
        group {
            id
            name
        }
        assignees {
            ...MemberFragment
        }
    }
}
