#import "./BaseFragment.gql"

mutation UpdateBase($input: UpdateBaseInput!) {
    updateBase(input: $input) {
        code
        success
        base {
            id
            node {
                ...Base
            }
        }
    }
}
