#import "../PinFragment.gql"

subscription PinUpdated($forNode: ID, $forMapping: ID) {
    pinUpdated {
        pin {
            ...Pin
        }
        pinboard {
            id
            count: pinsCount(forNode: $forNode, forMapping: $forMapping)
        }
    }
}
