#import "../PinboardWithCountFragment.gql"

query Pinboards(
    $spaceIds: [ID!],
    $forNode: ID,
    $forMapping: ID,
    $forLists: [ID!],
) {
    pinboards(
        spaceIds: $spaceIds,
        forLists: $forLists,
        first: 100,
    ) {
        edges {
            node {
                ...PinboardWithCount
            }
        }
        pageInfo {
            endCursor
            hasNextPage
        }
    }
}
