fragment ProgressTracker on ProgressTracker {
    id
    status
    processedCount
    totalCount
    progress
    message
    estimatedTimeRemaining
    startedAt
    finishedAt
    cancelledAt
    revertedAt
    revertFinishedAt
}
