name: Style lint check

on:
  pull_request_review:
    branches: [master]
    types: [submitted]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install modules
      run: yarn --cwd=frontend install

    - name: Lint CSS
      run: composer lint-style
