name: Type check

on:
  pull_request_review:
    branches: [master]
    types: [submitted]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    environment: staging_environment
    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: imagick, imap, redis, sockets, xdebug, zip, pdo_mysql

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      env:
        FIXER_API_KEY: ${{ secrets.FIXER_API_KEY }}
      run: |
        composer config http-basic.nova.laravel.com ${{ secrets.NOVA_USERNAME }} ${{ secrets.NOVA_PASSWORD }}
        composer install --no-progress --ignore-platform-reqs

    - name: Prepare environment
      run: |
        cp .env.ci .env
        php artisan key:generate

    - name: Type check
      env:
        FIXER_API_KEY: ${{ secrets.FIXER_API_KEY }}
        APP_ENV: ${{ vars.APP_ENV }}
        FILESYSTEM_DISK: ${{ vars.FILESYSTEM_DISK }}
        AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
        AWS_DOCUMENTS_BUCKET: ${{ vars.AWS_DOCUMENTS_BUCKET }}
        AWS_PUBLIC_BUCKET: ${{ vars.AWS_PUBLIC_BUCKET }}
        AWS_IMAGES_BUCKET: ${{ vars.AWS_IMAGES_BUCKET }}
      run: composer type-check-quiet
